config/routes.rb
Rails.application.routes.draw do
  get "search" => "searchs#search"
  devise_for :users
  root to: 'homes#top'
  get 'homes/top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/about' => 'homes#about'
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users do
   member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
  
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
 has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
 
 def follow(user_id)
  followers.create(followed_id: user_id)
 end

 def unfollow(user_id)
  followers.find_by(followed_id: user_id).destroy
 end

 def following?(user)
  following_users.include?(user)
 end	 
 
 def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
 end
 
 has_many :following_users, through: :followers, source: :followed
 has_many :follower_users, through: :followeds, source: :follower


  has_many :books, dependent: :destroy

  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }

def get_profile_image
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [100, 100]).processed
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end 
  
  def after_sign_out_path_for(resource)
    root_path
  end 

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :is_matching_login_user, only: [:edit, :update]
def new
  @book = Book.new
end

def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
  if @book.save
   flash[:notice] = "You have created book successfully."
   redirect_to book_path(@book)
  else
   @books = Book.all
   @user = @book.user
   render 'books/index'
  end
end

def show
  @book = Book.find(params[:id])
  @user = @book.user
  @comment = Comment.new
end

def index
  @books = Book.all
  @book = Book.new
  @user = current_user
end

def edit
  @book = Book.find(params[:id])
end

def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
  else
    render 'books/edit'
  end
end

def destroy
  book = Book.find(params[:id])
  book.destroy
  redirect_to '/books'
end

private
 def book_params
  params.require(:book).permit(:title, :body)
 end

 def is_matching_login_user
  @book = Book.find(params[:id])
  unless @book.user.id == current_user.id
    redirect_to '/books'
  end
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.comments.new(comment_params)
    comment.book_id = book.id
    comment.save
  end
  
  def destroy
    Comment.find(params[:id]).destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
  end 
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
  end 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end 
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @search_word = params[:word]
    @search_type = params[:search]
    @results_user, @results_book = User.looks(@search_type, @search_word), Book.looks(@search_type, @search_word)
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:seach], params[:word])
    else 
      @books = Book.looks(params[:seach], params[:word])
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @following_users = @user.following_users
    @follower_users = @user.follower_users
  end

  def index
    @users = User.all
    @user = current_user 
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else 
      render 'edit'
    end 
  end
  
  def follows
   user = User.find(params[:id])
   @users = user.following_users
  end
  
  def followers
   user = User.find(params[:id])
   @user = user.follower_users
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_users.html.erb
<h2>User info</h2>
  <% if current_user.profile_image.attached? %>
   <%= image_tag current_user.profile_image %>
  <% else %>
   <%= image_tag "default-image.jpg" %>
  <% end %>
 <table class="table">
   <tbody>
     <tr>
      <th>name</th>
      <th><%= @user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
     </tr>
     <tr>
     <th>Follows</th>
      <td>
        <%= link_to follows_user_path(@user) do %>
          <h6><%= @user.followers.count %></h6>
        <% end %> 
      </td>
      </tr>
      <tr>  
        <th>Followers</th>
        <td>  
          <%= link_to followers_user_path(@user) do %>
            <h6><%= @user.followeds.count %></h6>
          <% end %>
        </td>
      </tr> 
     <tr>
       <td>
        <% if current_user != @user %>
          <% if current_user.following?(@user) %>
            <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-info" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class:"btn btn-success" %>
          <% end %>
        <% end %>
      </td>
     </tr>
   </tbody>
  </table>
  <div class="row">
   <% if @user == current_user %>
    <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-cog" style="color: #5c5e60;"></i>
   <% end %>
   <% else %>
    <%= link_to edit_user_path, class: "btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-cog" style="color: #5c5e60;"></i>
    <% end %>
   <% end %>
  </div>
<h2 class="mt-3">New book</h2>
 <%= form_with model: Book.new do |f| %>
 <div>
  <p >Title</p>
  <%= f.text_field :title %>
 </div>
 <div>
  <p>Opinion</p>
  <%= f.text_area :body %>
 </div>
  <%= f.submit "Create Book", class: "btn btn-success btn-sm" %>
 <% end %>

app/views/books/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
      <h1>Editing Book</h1>
       <% if @book.errors.any? %>
       <%= @book.errors.count %> errors prohibited this obj from being saved:
       <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
       </ul>
      <% end %>
      <%= form_with model: @book do |f| %>
      <div>
        <p >Title</p>
        <%= f.text_field :title %>
      </div>
      <div>
       <p>Opinion</p>
       <%= f.text_area :body %>
      </div>
      <%= f.submit "Update Book", class: "btn btn-success btn-sm" %>
      <% end %>
       <%= link_to "Show", book_path(@book.id) %>
        | 
       <%= link_to "Back", '/books' %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
 <% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
           <th scope="col" style="width: 10%"></th>
           <th>Title</th>
           <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
           <tr>
            <td><a href="<%= user_path(book.user) %>"><%= image_tag book.user.get_profile_image, width: 80, height: 80 %></a></td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <%= form_with model: [book], local: false do |f| %>
            <td id="favorite_buttons_<%= book.id %>">
             <%= render "favorites/favorites", book: book %>
            </td>
            <% end %>
            <td>コメント件数：<%= @book.comments.count %></td>
          </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
 <%= flash[:notice] %>
<% end %>
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
　　　  <table class="table">
         <thead>
          <tr>
           <th>
             <%= image_tag @book.user.get_profile_image, width: 80, height: 80 %><br>
             <%= link_to @book.user.name, user_path(@book.user) %>
           </th>
           <th><%= link_to @book.title, book_path(@book) %></th>
           <th><%= @book.body %></th>
           <th>
             <% if @book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(@book), method: :delete, class: "text-danger" do %>
              ♥<%= @book.favorites.count %>
             <% end %>
             <% else %>
               <%= link_to book_favorites_path(@book), method: :post do %>
               ♥<%= @book.favorites.count %>
             <% end %>
            <% end %>
           </th>
           <th>コメント件数：<%= @book.comments.count %></th>
            <% if @book.user == current_user %>
             <th>
               <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success btn-sm" %>
             </th>
             <th>
              <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm" %>
             </th>
            <% end %>
          </tr>
         </thead>
        <tbody>
         <td id="comments">
          <%= form_with model: [ @book,@comment ], local: false do |f| %>
           <%= render "comments/comment" , { book: @book , comment: @comment } %>
          <% end %>
         </td>
      </tbody>
     </table>
       <%= form_with model: [@book, @comment] do |f| %>
         <%= f.text_area :comment,   rows: 5, cols: 80 %>
         <%= f.submit "送信する" %>
       <% end %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<% @book.comments.each do |comment| %>
  <tr>
    <td>
      <%= image_tag comment.user.get_profile_image, width: 80, height: 80 %>
      <%= comment.user.name %>
      <%= comment.comment %>
      <% if comment.user == current_user %>
      <%= link_to "Destroy", book_comment_path(@book, comment), method: :delete, remote:true, data: {"turbolinks" => false}, class: "btn btn-danger btn-sm" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/comments/create.js.erb
$('#comments').html("<%= j(render "comments/comment", book: @book) %>");

app/views/comments/destroy.js.erb
$('#comments').html("<%= j(render "comments/comment", book: @book) %>");

app/views/favorites/_favorites.html.erb
 <% if book.favorited_by?(current_user) %>
   <%= link_to book_favorites_path(book), method: :delete, remote: true, data: {"turbolinks" => false}, class: "text-danger" do %>
    ♥<%= book.favorites.count %>
   <% end %>
 <% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true, data: {"turbolinks" => false} do %>
      ♥<%= book.favorites.count %>
    <% end %>
 <% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="mt-3">
   <div class="row">
    <h1 class="mx-auto col-md-">Welcome to
      <i class="fa-solid fa-book" style="color: #000000;"></i><strong>Bookers</strong>!
    </h1>
   </div>
  </div>
</div>

app/views/homes/top.html.erb
<% if flash[:notice] %>
   <%= flash[:notice] %>
<% end %>
<div class="container">
 <div class="mt-4">
 <div class="row">
  <div class="mx-auto col-6">
  <h1>welcome to
   <i class="fa-solid fa-book" style="color: #000000;"></i><strong>Bookers</strong>!!
  </h1>

  <p>In
   <i class="fa-solid fa-book" style="color: #000000;"></i><strong>Bookers</strong>,
  </p>

  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>
 
   <div class="col-10 mx-auto">
    <div class="row">
     <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
    </div>
    <div class="row">
     <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
    </div>
   </div>
  </div>
 </div>
 </div>
</div>

app/views/searchs/search.html.erb
<table class="table table-hover table-inverse">
  <% if @range == "User" %>
   <h2>User search for "<%= @search_word %>"</h2>
    <tbody>
      <% @results_user.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image, width: 80, height: 80 %></td>
          <td><%= user.name %></td>
          <td>フォロー<%= user.followers.count %></td>
          <td>フォロワー<%= user.followeds.count %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
   <h2>Books search for "<%= @search_word %>"</h2>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @results_book.each do |book| %>
        <tr>
          <td><a href="<%= user_path(book.user) %>"><%= image_tag book.user.get_profile_image, width: 80, height: 80 %></a></td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/_users.html.erb
<h2>User info</h2>
  <% if current_user.profile_image.attached? %>
   <%= image_tag current_user.profile_image %>
  <% else %>
   <%= image_tag "default-image.jpg" %>
  <% end %>
 <table class="table">
   <tbody>
     <tr>
      <th>name</th>
      <th><%= @user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
     </tr>
     <tr>
     <th>Follows</th>
      <td>
        <%= link_to follows_user_path(@user) do %>
          <h6><%= @user.followers.count %></h6>
        <% end %> 
      </td>
      </tr>
      <tr>  
        <th>Followers</th>
        <td>  
          <%= link_to followers_user_path(@user) do %>
            <h6><%= @user.followeds.count %></h6>
          <% end %>
        </td>
      </tr> 
     <tr>
       <td>
        <% if current_user != @user %>
          <% if current_user.following?(@user) %>
            <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-info" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class:"btn btn-success" %>
          <% end %>
        <% end %>
      </td>
     </tr>
   </tbody>
  </table>
  <div class="row">
   <% if @user == current_user %>
    <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-cog" style="color: #5c5e60;"></i>
   <% end %>
   <% else %>
    <%= link_to edit_user_path, class: "btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-cog" style="color: #5c5e60;"></i>
   <% end %>
   <% end %>
  </div>
<h2 class="mt-3">New book</h2>
 <%= form_with model: Book.new do |f| %>
 <div class="form-group">
  <p >Title</p>
  <%= f.text_field :title %>
 </div>
 <div class="form-group">
  <p>Opinion</p>
  <%= f.text_area :body %>
 </div>
 <div class="form-group">
  <%= f.submit "Create Book", class: "btn btn-success btn-sm" %>
 </div>
 <% end %>

app/views/users/edit.html.erb
<div class="container mt-3">
 <div class="row">
   <div class="mx-auto">
    <%= form_with model: @user do |f| %>
    <h2>User info</h2>
     <% if @user.errors.any? %>
      <%= @user.errors.count %> errors prohibited this obj from being saved:
      <ul>
       <% @user.errors.full_messages.each do |message| %>
       <li><%= message %></li>
       <% end %>
      </ul>
      <% end %>
    <div>
     <%= f.label :name %><br>
     <%= f.text_field :name %>
    </div>
    <div>
     <%= f.label :image %><br>
     <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
    </div>
    <div>
     <%= f.label :introduction %><br>
     <%= f.text_area :introduction %>
    </div>
    <%= f.submit "Update User", class: "btn btn-secondary btn-sm" %>
    <% end %>
   </div>
  </div>
 </div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= image_tag user.get_profile_image %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>
          <%= link_to follows_user_path(user) do %>
            <p>フォロー<%= user.followers.count %></p>
          <% end %>
        </td>
        <td>
          <%= link_to followers_user_path(user) do %>
            <p>フォロワー<%= user.followeds.count %></p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
  <table class='table'>
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user) do %>
              <%= image_tag user.get_profile_image, width: 80, height: 80 %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td>
            <%= link_to follows_user_path(user) do %>
              <h6>フォロー<%= user.followers.count %></h6>
            <% end %>
          </td>
          <td>
            <%= link_to followers_user_path(user) do %>
              <h6>フォロワー<%= user.followeds.count %></h6>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render "users" %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image, width: 80, height: 80 %></td>
              <td><%= user.name %></td>
              <td>フォロー<%= user.followers.count %></td>
              <td>フォロワー<%= user.followeds.count %></td>
              <td>
                <% if current_user.following?(user) %>
                 <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                <% else %>
                 <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                <% end %>
              </td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
 <%= flash[:notice] %>
<% end %>
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render "users" %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
         <% @user.books.each do |book| %>
      　　<tr>
      　　   <td><a href="<%= user_path(book.user) %>"><%= image_tag @user.get_profile_image, width: 80, height: 80%></td>
           <td><%= link_to book.title, book_path(book) %></td>
           <td><%= book.body %></td>
          </tr>
         <% end %>
        </tbody>
      </table>
  </div>
</div>